//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Country1 { get; set; }
        public string isocode { get; set; }
        public string DialCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> entityId { get; set; }
    }
}
