//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_CaseType
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string CaseGroup { get; set; }
        public string CaseType { get; set; }
        public string Description { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> clientId { get; set; }
        public string CaseFor { get; set; }
    }
}
