//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_Sm_studentinfo
    {
        public int Id { get; set; }
        public string StudentID { get; set; }
        public string grno { get; set; }
        public string StudentCategory { get; set; }
        public string FullName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string CNIC { get; set; }
        public string Nationality { get; set; }
        public string gender { get; set; }
        public string Religon { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Phoneno { get; set; }
        public string mobileno { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> joingdate { get; set; }
        public Nullable<System.DateTime> admissiondate { get; set; }
        public string syllabus { get; set; }
        public string Course { get; set; }
        public string Section { get; set; }
        public string Sectiongroup { get; set; }
        public string fatherName { get; set; }
        public string fatherincome { get; set; }
        public string Contactno { get; set; }
        public string fathercnic { get; set; }
        public string whatsappno { get; set; }
        public string fatheremail { get; set; }
        public string fatheraddress { get; set; }
        public string fathercountry { get; set; }
        public string fatherstate { get; set; }
        public string fathercity { get; set; }
        public string mothername { get; set; }
        public string mothercnic { get; set; }
        public string mothercontactno { get; set; }
        public string motherwhatsapp { get; set; }
        public string motheremail { get; set; }
        public string motheraddres { get; set; }
        public string mothercountry { get; set; }
        public string motherstate { get; set; }
        public string mothercity { get; set; }
        public string emergencyrelagion { get; set; }
        public string emergencypersonname { get; set; }
        public string emergencycnic { get; set; }
        public string emergencycontactno { get; set; }
        public Nullable<int> entityId { get; set; }
    }
}
