//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_Ac_bookAuthor
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string AuthorType { get; set; }
        public string NickName { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string YearBorn { get; set; }
        public string YearDied { get; set; }
        public string Awards { get; set; }
        public int entityId { get; set; }
    }
}
