//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_AC_Subject
    {
        public int Id { get; set; }
        public Nullable<int> entityId { get; set; }
        public string Code { get; set; }
        public string SubjectType { get; set; }
        public string Course { get; set; }
        public string Language { get; set; }
        public string PeriodsPerWeek { get; set; }
        public string SubjectName { get; set; }
        public string SubjectCategory { get; set; }
        public string SubjectClass { get; set; }
        public string Compulsory { get; set; }
        public string Syllabus { get; set; }
    }
}
