//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_SMBatch
    {
        public int Id { get; set; }
        public string bookno { get; set; }
        public string bookdate { get; set; }
        public string booktype { get; set; }
        public string boojname { get; set; }
        public string status { get; set; }
        public string academicyearid { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string prefix { get; set; }
        public string counter { get; set; }
        public string masklength { get; set; }
        public string totalseats { get; set; }
        public string enrolled { get; set; }
        public string available { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
