//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_HR_EmployeeProfile
    {
        public int Id { get; set; }
        public Nullable<int> empid { get; set; }
        public string shrotcode { get; set; }
        public string machinecode { get; set; }
        public string joindate { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string dateofbirth { get; set; }
        public string Gender { get; set; }
        public string bloodgroup { get; set; }
        public string CNIC { get; set; }
        public string birthcountry { get; set; }
        public string birthcity { get; set; }
        public string nationality { get; set; }
        public string religion { get; set; }
        public string email { get; set; }
        public string contactno { get; set; }
        public string whatsappno { get; set; }
        public string emptype { get; set; }
        public string empcategory { get; set; }
        public string empdepartment { get; set; }
        public string empdestination { get; set; }
        public string site { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
