//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_SMAcademicYear
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string academicregister { get; set; }
        public string academicyear { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string syllabus { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> cleintid { get; set; }
    }
}
