//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_Ac_Book
    {
        public int Id { get; set; }
        public string bookno { get; set; }
        public string course { get; set; }
        public string Subject { get; set; }
        public string subtype { get; set; }
        public string bookname { get; set; }
        public string tag { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public string barcode { get; set; }
        public string price { get; set; }
        public string edition { get; set; }
        public string year { get; set; }
        public string seriesname { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
