//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdr_FOAdmEnquiry
    {
        public int Id { get; set; }
        public string enquiryno { get; set; }
        public string enquirydate { get; set; }
        public string campus { get; set; }
        public string sourcetypeid { get; set; }
        public string applicantname { get; set; }
        public string cnic { get; set; }
        public string dateofbirth { get; set; }
        public string genderid { get; set; }
        public string applyforid { get; set; }
        public string preclassattid { get; set; }
        public string preschoolname { get; set; }
        public string address { get; set; }
        public string coutryid { get; set; }
        public string stateid { get; set; }
        public string cityid { get; set; }
        public string cellno { get; set; }
        public string whatsappno { get; set; }
        public string email { get; set; }
        public string preferrescommunication { get; set; }
        public string fathername { get; set; }
        public string fathercnic { get; set; }
        public string fatheroccupationid { get; set; }
        public string fatherrganization { get; set; }
        public string fathercellno { get; set; }
        public string fatherwhatsapp { get; set; }
        public string fatheremail { get; set; }
        public string fatherpreferrescommunication { get; set; }
        public string mothername { get; set; }
        public string mothercnic { get; set; }
        public string motheroccupationid { get; set; }
        public string motherrganization { get; set; }
        public string mothercellno { get; set; }
        public string motherwhatsapp { get; set; }
        public string motheremail { get; set; }
        public string motherpreferrescommunication { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
