//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_SMFeetype
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string sharedwith { get; set; }
        public string feecat { get; set; }
        public string feebaseon { get; set; }
        public string feetype { get; set; }
        public string taxable { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
