//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_user_Entity
    {
        public int Id { get; set; }
        public Nullable<int> userId { get; set; }
        public string EntityName { get; set; }
        public Nullable<int> clientId { get; set; }
    
        public virtual ut_user_auth ut_user_auth { get; set; }
    }
}
