//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_usermoudulesrights
    {
        public int Id { get; set; }
        public Nullable<int> roleid { get; set; }
        public string modulename { get; set; }
        public string routerLink { get; set; }
        public string moduleimg { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
