//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstSM_MonthlyFeeStudent_Detail
    {
        public int Id { get; set; }
        public Nullable<int> monthfeeid { get; set; }
        public string stdid { get; set; }
        public string grno { get; set; }
        public string stdname { get; set; }
        public string fathername { get; set; }
        public string course { get; set; }
        public string section { get; set; }
        public string monthlyfee { get; set; }
        public string dis_amount { get; set; }
        public Nullable<int> entityId { get; set; }
        public string clientId { get; set; }
    
        public virtual mstSM_MonthlyFee mstSM_MonthlyFee { get; set; }
    }
}
