//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstSM_MonthlyFee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstSM_MonthlyFee()
        {
            this.mstSM_MonthlyFeeStudent_Detail = new HashSet<mstSM_MonthlyFeeStudent_Detail>();
        }
    
        public int Id { get; set; }
        public string entity { get; set; }
        public string course { get; set; }
        public string section { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string duedate { get; set; }
        public string latefeeamount { get; set; }
        public Nullable<int> entityId { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> stdid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstSM_MonthlyFeeStudent_Detail> mstSM_MonthlyFeeStudent_Detail { get; set; }
    }
}
