//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMActivitiesSTUDENTAttendance
    {
        public int Id { get; set; }
        public string stdid { get; set; }
        public string stdname { get; set; }
        public string courseid { get; set; }
        public string sectionid { get; set; }
        public string gender { get; set; }
        public DateTime attenDate { get; set; }
        public string attenTime { get; set; }
        public string attendactivity { get; set; }
        public string entityId { get; set; }
    }
}
