//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms_Qualification
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string qualificationtypeid { get; set; }
        public string qualification { get; set; }
        public string Description { get; set; }
        public Nullable<int> entityid { get; set; }
    }
}
