//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecmapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMStuAttendance
    {
        public int Id { get; set; }
        public Nullable<int> stdid { get; set; }
        public string courseid { get; set; }
        public string sectionid { get; set; }
        public string attenDate { get; set; }
        public string attendactivity { get; set; }
        public Nullable<int> entityId { get; set; }
    }
}
